name = "dbt SQL"
grammar = "sql"
path_suffixes = ["sql"]
line_comments = ["-- "]
tab_size = 2
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
]
word_characters = ["_"]
